services:
  frontend:
    image: "${IMAGE_NAME}"
    container_name: "${CONTAINER_NAME}"
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`$HOST`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

    networks:
      - proxy

networks:
  proxy:
    external: true
